name: "DAST with ZAP"

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Target URL for DAST scan'
        required: false
        default: 'https://staging.hustleriq.com'
        type: string
  schedule:
    - cron: '0 2 * * 0'  # Weekly on Sunday at 2 AM

permissions:
  contents: read

jobs:
  dast-zap:
    name: "ZAP DAST Scan"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit
          allowed-endpoints: >
            github.com:443
            api.github.com:443
            staging.hustleriq.com:443

      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set target URL
        id: target
        env:
          INPUT_URL: ${{ github.event.inputs.target_url }}
        run: |
          if [ "${INPUT_URL}" != "" ]; then
            echo "target_url=${INPUT_URL}" >> "${GITHUB_OUTPUT}"
          else
            echo "target_url=https://staging.hustleriq.com" >> "${GITHUB_OUTPUT}"
          fi

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@a6d84c7f3d0b0bb8bff9dfe7c98d0b2b57104ba7 # v0.13.0
        with:
          target: ${{ steps.target.outputs.target_url }}
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

      - name: Generate ZAP Report
        run: |
          if [ -f report_html.html ]; then
            echo "ZAP scan completed successfully"
            echo "Report available as artifact"
          else
            echo "No ZAP report generated"
          fi

      - name: Upload ZAP Results
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        if: always()
        with:
          name: zap-report
          path: |
            report_html.html
            report_json.json
          retention-days: 7

      - name: ZAP to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@2c779ab0d087cd7fe7b826087247c2c81f27bfa6 # v3.26.7
        if: always()
        with:
          sarif_file: report_json.json
          category: 'DAST-ZAP'

      - name: Fail on High Risk Issues
        run: |
          if [ -f report_json.json ]; then
            HIGH_RISK=$(jq -r '.site[0].alerts[] | select(.riskdesc | startswith("High")) | .riskdesc' report_json.json 2>/dev/null | wc -l || echo "0")
            if [ "${HIGH_RISK}" -gt "0" ]; then
              echo "Found ${HIGH_RISK} high-risk security issues"
              jq -r '.site[0].alerts[] | select(.riskdesc | startswith("High")) | "- \(.name): \(.desc)"' report_json.json
              exit 1
            else
              echo "No high-risk security issues found"
            fi
          else
            echo "No ZAP report to analyze"
          fi
